services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  doctor-service:
    build:
      context: ./doctor-service
      dockerfile: /Dockerfile
    container_name: doctor-service
    ports:
      - "8081:50051"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - PORT=:50051
    depends_on:
      - mongodb
    restart: on-failure

  appoitment-service:
    build:
      context: ./appoitment-service
      dockerfile: /Dockerfile
    container_name: appoitment-service
    ports:
      - "8082:50052"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - PORT=:50052
      - DOCTOR_SERVICE_URL=doctor-service:50051
    depends_on:
      - mongodb
      - doctor-service
    restart: on-failure

volumes:
  mongo-data:
